from __future__ import annotations

import ast
import hashlib
import re
from pathlib import Path
from typing import Iterable

_ALLOWLIST_COMMENT_RE = re.compile(
    r"#\s*(?:noqa|autoforensics-skip)\s*:\s*([\w.\-]+(?:\s*,\s*[\w.\-]+)*)"
)


# ---------------------------------------------------------------------------
# F16d: Generated / sanctioned-asset-bundle detector.
# Opt-in marker pattern: size + structural gates can skip files whose first
# few lines carry one of the markers below. Markers must be explicit — regular
# code cannot be accidentally skipped.
# ---------------------------------------------------------------------------

_GENERATED_MARKERS = (
    "# autogenerated",
    "# auto-generated",
    "# Generated by",
    "# DO NOT EDIT",
    "# This file is auto-generated",
    "@generated",
    "# @generated",
    "# SANCTIONED_ASSET_BUNDLE",  # Vigil convention for sanctioned bundles
)


def is_generated_file(source: str, max_lines: int = 10) -> bool:
    """Return True if *source* has a generator/sanctioned marker in first N lines.

    F16d false-positive reduction: size + structural gates (size.*, god_object_zones.*)
    use this to skip auto-generated files and sanctioned asset bundles. The check
    is strictly opt-in -- regular code cannot be accidentally skipped because it
    would have to voluntarily carry one of the listed markers in its head.

    Matching rules:
      - Case-insensitive substring match inside the stripped line.
      - Only the first *max_lines* lines are inspected (default 10).
      - Empty / missing source returns False (fail-open).
    """
    if not source:
        return False
    head = source.splitlines()[:max_lines]
    lowered_markers = [m.lower() for m in _GENERATED_MARKERS]
    for line in head:
        stripped = line.strip().lower()
        for marker in lowered_markers:
            if marker in stripped:
                return True
    return False


def has_allowlist_for(content: str, check_id: str, line_number: int | None = None) -> bool:
    """Check if finding should be suppressed by inline allowlist comment.

    Patterns supported:
      # noqa: check_id
      # noqa: check_id, other_check
      # autoforensics-skip: check_id

    If line_number provided: check same line or previous line.
    If line_number None: check entire file for file-level allowlist (first 20 lines).
    """
    lines = content.splitlines()
    if line_number is not None and 1 <= line_number <= len(lines):
        candidates = [lines[line_number - 1]]
        if line_number >= 2:
            candidates.append(lines[line_number - 2])
    else:
        candidates = lines[:20]

    for line in candidates:
        for match in _ALLOWLIST_COMMENT_RE.finditer(line):
            ids = [x.strip() for x in match.group(1).split(",")]
            if check_id in ids or any(check_id.startswith(i + ".") for i in ids):
                return True
    return False

from cortex_forensic._shared import EvidenceReference, GateCategory, GateCheckResult, GateFileSnapshot, GateFinding, GateImpact, GateSeverity
from cortex_forensic.gate_models import PostExecGateContext
import logging
_log = logging.getLogger(__name__)


def normalize_path(path: str) -> str:
    return str(path or "").replace("\\", "/").lstrip("./")


def build_finding(
    *,
    check_id: str,
    category: GateCategory,
    title: str,
    severity: GateSeverity,
    impact: GateImpact,
    summary: str,
    recommendation: str,
    evidence: Iterable[EvidenceReference] = (),
    repair_kind: str = "",
    executor_action: str = "",
    proof_required: str = "",
    allowlist_allowed: bool = True,
    preferred_fix_shape: str = "",
    # Sprint A (2026-04-23): confidence/applicability layer. Defaults preserve
    # legacy semantics (every gate call that does not opt in emits an
    # "applicable" finding with full detector confidence). Fingerprint
    # computation below deliberately excludes these fields so allowlist
    # stability is preserved as gates gradually migrate.
    confidence: float = 1.0,
    applicability: str = "applicable",
    analysis_mode: str = "heuristic",
    applicability_reason: str = "",
) -> GateFinding:
    evidence_tuple = tuple(evidence)
    # Fingerprint policy (unchanged): check_id|category|title|impact|evidence_paths.
    # New Sprint A fields are intentionally excluded — confidence drifts with
    # signal learning; including it would invalidate existing allowlists.
    fingerprint = hashlib.sha256(
        "|".join(
            [check_id, category.value, title, impact.value]
            + [item.path or item.detail for item in evidence_tuple]
        ).encode("utf-8")
    ).hexdigest()[:16]
    return GateFinding(
        check_id=check_id,
        category=category,
        title=title,
        severity=severity,
        impact=impact,
        summary=summary,
        recommendation=recommendation,
        evidence=evidence_tuple,
        fingerprint=fingerprint,
        repair_kind=repair_kind,
        executor_action=executor_action,
        proof_required=proof_required,
        allowlist_allowed=allowlist_allowed,
        preferred_fix_shape=preferred_fix_shape,
        confidence=confidence,
        applicability=applicability,
        analysis_mode=analysis_mode,
        applicability_reason=applicability_reason,
    )


def build_check_result(
    *,
    check_id: str,
    category: GateCategory,
    findings: Iterable[GateFinding] = (),
    notes: Iterable[str] = (),
) -> GateCheckResult:
    return GateCheckResult(
        check_id=check_id,
        category=category,
        findings=tuple(findings),
        notes=tuple(str(item) for item in notes if str(item).strip()),
    )


def read_snapshot(project_dir: Path, path: str) -> GateFileSnapshot:
    repo_path = normalize_path(path)
    abs_path = project_dir / repo_path
    if not abs_path.exists() or not abs_path.is_file():
        return GateFileSnapshot(path=repo_path, exists=False, size=0, line_count=0, text="")
    text = abs_path.read_text(encoding="utf-8-sig", errors="replace")
    return GateFileSnapshot(
        path=repo_path,
        exists=True,
        size=abs_path.stat().st_size,
        line_count=len(text.splitlines()),
        text=text,
    )


def iter_touched_snapshots(ctx: PostExecGateContext) -> list[GateFileSnapshot]:
    snapshots: list[GateFileSnapshot] = []
    for path in ctx.touched_files:
        normalized = normalize_path(path)
        if normalized in ctx.file_snapshots:
            snapshots.append(ctx.file_snapshots[normalized])
        else:
            snapshots.append(read_snapshot(ctx.project_dir, normalized))
    return snapshots


def hash_normalized_code(text: str) -> str:
    normalized = re.sub(r"\s+", " ", re.sub(r"\b[A-Za-z_][A-Za-z0-9_]*\b", "ID", text.strip()))
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def hash_text_block(text: str) -> str:
    """Hash for text-block dedup: whitespace-only normalization, identifiers preserved.

    Unlike hash_normalized_code (which replaces all identifiers with 'ID' for structural
    similarity), this preserves actual names -- catching literal copy-paste rather than
    structural coincidence (e.g. two unrelated dataclasses with the same field count).
    """
    normalized = re.sub(r"\s+", " ", text.strip())
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def extract_python_functions(text: str) -> list[tuple[str, int, int, str]]:
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    lines = text.splitlines()
    results: list[tuple[str, int, int, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        start = int(getattr(node, "lineno", 1))
        end = int(getattr(node, "end_lineno", start))
        snippet = "\n".join(lines[start - 1:end])
        results.append((str(node.name), start, end, snippet))
    return results


def max_nesting_depth(text: str) -> int:
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return 0

    def _depth(node: ast.AST, current: int = 0) -> int:
        next_depth = current
        if isinstance(node, (ast.For, ast.AsyncFor, ast.While, ast.If, ast.With, ast.Try, ast.Match)):
            next_depth += 1
        child_depths = [_depth(child, next_depth) for child in ast.iter_child_nodes(node)]
        return max([next_depth, *child_depths], default=next_depth)

    return _depth(tree, 0)


# ---------------------------------------------------------------------------
# F14c: Detector self-match suppression helpers
# ---------------------------------------------------------------------------
# Canonical implementation lives in ._ast_helpers (introduced in F14a).
# Re-export for backwards compatibility so gates can import these names from
# either ``..common`` or ``.._ast_helpers``.
from ._ast_helpers import (  # noqa: E402, F401  -- public re-export
    collect_constant_container_literal_lines,
    is_section_header_comment,
    is_cli_surface_file,
    collect_main_block_line_ranges,
    line_in_ranges,
)
